import './globals.css'

export const metadata = {
  title: 'Innovative World',
  description: 'Generated by Innovative World',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
